# Generated by Django 4.1.4 on 2023-01-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_email_messaje_nombre_subject_delete_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('mensaje', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='opinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('opinion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='reservar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('diaInicio', models.IntegerField(max_length=2)),
                ('diaFin', models.IntegerField(max_length=2)),
                ('mes', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Messaje',
        ),
        migrations.DeleteModel(
            name='Nombre',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
